version: '3'

services:
  postgres:
    container_name: Database-Postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker/sql-scripts/:/docker-entrypoint-initdb.d/
      - ./docker/postgres-data:/var/lib/postgresql/data
    networks:
      [ "rede" ]

  chess-api:
    container_name: Chess-API
    build:
      context: ChessApp/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./ChessApp:/ChessApp
    networks:
      ["rede"]

  react-page:
    container_name: React-page
    build:
      context: PageApp/app
    ports:
      - "3000:3000"
    volumes:
      - ./PageApp:/PageApp
    networks:
      [ "rede" ]

networks:
  rede: